services:
  app:
    container_name: homelib-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - .src/:/app/src
    networks:
      - homelib-net
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file:
      - .env
    volumes:
      - postgress-db-volume:/var/lib/postgresql/data
    networks:
      - homelib-net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always


volumes:
  postgress-db-volume:

networks:
  homelib-net:
    driver: bridge
